# Build using Python 3.6
language: python
python:
- 3.6
# Cache Dependencies
cache: pip
branches:
  only:
  - master
# install dependencies
install:
- pip install --upgrade pip
- pip install -r legacy_site/requirements.txt
- pelican-themes -vi ./legacy_site/pelican-themes/Flex
before_script:
  - cd legacy_site && invoke --list && cd ..
script:
  - cd legacy_site && invoke publish-carefully

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: output
  on:
    branch: master
